### ISSUE TITLE
File Format

### ISSUE THREAD

**Issue by AKSoapy29** [cowai/camerarawpreviews#1] opened 2017-03-27 21:05 UTC
Hi. What file formats does your app support? I was looking through the app code to see if I could figure it out and expand it to Sony's ARW format. Maybe I have the NextCloud environment setup wrong?

**Comment by cowai** [comment] 2017-03-27 21:13
@AKSoapy29 I have not tried ARW. If exiftool can extract a preview image then it should work. Provided that the reported mimetype by nextcloud is "image/x-dcraw". Have you had success with a normal CR2 file?

Try this as a first test:
```shell
$ exiftool -b -PreviewImage test.arw > preview.jpg

**Comment by cowai** [comment] 2017-03-27 21:16
Oops, I accidently closed this issue. That was not my intention.

@AKSoapy29 If that command fails. You can try this one too:
```shell
$ exiftool -b -ThumbnailImage test.arw > preview.jpg

**Comment by AKSoapy29** [comment] 2017-03-27 21:32
I tried -PreviewImage, and that worked. I did not try -ThumbnailImage. I found a CR2 file online to test with, and it doesn't look like it generates a thumbnail in NextCloud. The 'camerarawpreviews' folder just goes in the 'apps' directory, correct? I don't think NextCloud is recognizing it.

**Comment by cowai** [comment] 2017-03-27 21:39
Yes, correct. You put it in the apps/ folder. And then you need to add the configuration as mentioned in readme.md.
After that you can enable the app in the app list in nextcloud.

It also may very well be that you need to add the proper mimetypes  (see official admin documentation for that) to your nextcloud installation, but I am not totally sure.

**Comment by AKSoapy29** [comment] 2017-03-27 21:49
I checked in the app list after I installed it, but I didn't see anything. Could permissions on the files / directory effect something?

**Comment by cowai** [comment] 2017-03-27 21:51
Maybe. Make the files is owned by the same user that php runs as and it should be ok. What version of nextcloud are you running?

⁣Sent from BlueMail ​

**Comment by AKSoapy29** [comment] 2017-03-27 21:51
The latest: 11.0.2.

**Comment by cowai** [comment] 2017-03-27 21:57
I would try to install other apps the same way to determine if there is anything specific with my app or not.

⁣Sent from BlueMail ​

**Comment by AKSoapy29** [comment] 2017-03-27 22:19
Well I'm obviously doing something wrong, but I don't know what :/ I can't get a different app working either. I tried Theme Switcher: https://apps.owncloud.com/content/show.php/Theme+Switcher?content=173857

**Comment by bspradling8** [comment] 2017-09-21 16:05
I'm kind of running into this same issue. I'm looking to get ARW images working but after installing. I can see CameraRawPreviews in the app list, however, the Enable button is greyed out and there is another button next to it wanting me to remove the application. Do you know of a way to get it enabled?

**Comment by cowai** [comment] 2017-09-22 14:07
What version do you have?
Maybe you can try to enable it with occ command? Maybe you get an error message that you can look up. Also check the nextcloud log for any thing related.

Do you have all the requirements for the app? Like exiftool, adding the needed config. Correct mimetype mappings for your format. Also, I am not sure if ARW works right yet.

**Comment by stowel** [comment] 2017-10-08 12:18
@bspradling8 Did you tried to enable the app with occ command?

1. Switch to nc install dir
2. run: `sudo -u www-data php occ app:enable camerarawpreviews`

I've enabled camerapreview like this, installed exiftool, ImageMagick and Magick-Php5, added following lines to my config.php `... 'preview_max_filesize_image' => 500,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\FB2',
    6 => 'OC\\Preview\\PDF',
    7 => 'OCA\\CameraRawPreviews\\RawPreview',
    8 => 'OCA\\CameraRawPreviews\\IndesignPreview'
  ),
...`
JPG, PNG, TIFF Preview is working, but with raw files (DNG, CR2) I get the error: 

> Error! Preview can't generate file....

and in nextcloud.log: 

> .... "app":"gallery","method":"GET","url":"\/apps\/gallery\/preview\/312900?width=2000&height=2000&c=7aed1484dda22268b86d6bb6afec2b24&requesttoken=xljm236xHJuIsrPDW2PxfqcGYh6oK5S4XFFz0bH%2BOAU%3D%3ArQHW8FGCVd%2Fi1oexHiSDEssyAEaeBN7pOhcEuIbVQEk%3D","message":"Exception: Preview generation has failed" ....

**Comment by cowai** [comment] 2017-10-08 12:23
I should find some time to write a good how to. I think the thing you are
missing now is correct mimetypes. But not really sure about that.

On Oct 8, 2017 14:18, "stowel" <notifications@github.com> wrote:

@bspradling8 <https://github.com/bspradling8> Did you tried to enable the
app with occ command?

   1. Switch to nc install dir
   2. run: sudo -u www-data php occ app:enable camerarawpreviews

I've enabled camerapreview like this, installed exiftool, ImageMagick and
Magick-Php5, added following lines to my config.php ...
'preview_max_filesize_image' => 500, 'enabledPreviewProviders' => array ( 0
=> 'OC\\Preview\\Image', 1 => 'OC\\Preview\\MP3', 2 => 'OC\\Preview\\TXT',
3 => 'OC\\Preview\\MarkDown', 4 => 'OC\\Preview\\Epub', 5 =>
'OC\\Preview\\FB2', 6 => 'OC\\Preview\\PDF', 7 =>
'OCA\\CameraRawPreviews\\RawPreview',
8 => 'OCA\\CameraRawPreviews\\IndesignPreview' ), ...
JPG, PNG, TIFF Preview is working, but with raw files (DNG, CR2) I get the
error:

Error! Preview can't generate file....

and in nextcloud.log:

.... "app":"gallery","method":"GET","url":"/apps/gallery/preview/
312900?width=2000&height=2000&c=7aed1484dda22268b86d6bb6afec2b
24&requesttoken=xljm236xHJuIsrPDW2PxfqcGYh6oK5S4XFFz0bH%2BOAU%3D%
3ArQHW8FGCVd%2Fi1oexHiSDEssyAEaeBN7pOhcEuIbVQEk%3D","message":"Exception:
Preview generation has failed" ....

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/cowai/camerarawpreviews/issues/1#issuecomment-335002740>,
or mute the thread

**Comment by stowel** [comment] 2017-10-08 20:13
What mimetypes should I change/add?

In ./resources/config/mimetypemapping.dist.json both formats are already present:
```
...
"dng": ["image/x-dcraw"],
"cr2": ["image/x-dcraw"],
...
```

**Comment by cowai** [comment] 2017-10-08 20:17
That is the correct ones. How much memory do you allow php?

**Comment by stowel** [comment] 2017-10-14 15:10
I've set no memory limit (value -1), the server got around 10GB free RAM. ...

> php.ini:
> .... 
> ; Maximum amount of memory a script may consume (128MB)
> ; http://php.net/memory-limit
> memory_limit = -1
> ...

**Comment by cowai** [comment] 2017-10-15 11:52
@stowel 
What happens when you see the file in the files app? Do you get a preview or an attempt at an loading preview at all?

**Comment by stowel** [comment] 2017-10-16 07:07
After I tried to update mimetype.js with:

`php occ maintenance:mimetype:update-js`

nc is not showing the preview plugin anymore and starts downloading cr2 and dng files directly. Before that the preview plugin loads and shows a black screen with the message 

> Error! Preview can't generate file....

Looks like it getting even worse... :-(

**Comment by cowai** [comment] 2017-10-16 08:36
I think you can see the mimetype of the file by checking with webdav output.

**Comment by bspradling8** [comment] 2017-11-01 06:21
Sorry I'm late getting back to this.  I was finally able to run the `occ` command to try and enable CameraRawPreviews. I get back the following: ```[Exception]
  App "CameraRawPreviews" cannot be installed because it is not compatible with this version of the server.```

I'm running the latest via Docker. What version does CameraRawPreviews support?

**Comment by cowai** [comment] 2017-12-08 07:07
Right now 13 is specified in appinfo. Did you get it working? @bspradling8

**Comment by cowai** [comment] 2018-04-02 16:28
No answer. Please reopen if the issue is not resolved.

**Closed by cowai** 2018-04-02 16:28 UTC
